name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches: main 
  workflow_dispatch:        # manual “Run workflow” button

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.10.18
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.18
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Build the page
    - name: Build the book
      run: |
        jupyter-book build lecture/
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./lecture/_build/html
